# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, upload_to='projects/')),
                ('repoUrl', models.CharField(max_length=50)),
                ('deployedUrl', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
